# Generated by Django 3.0.5 on 2020-05-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Property Type',
                'verbose_name_plural': 'Property Type',
            },
        ),
        migrations.CreateModel(
            name='SaleStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Sales Status',
                'verbose_name_plural': 'Sales Status',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'Property Style',
                'verbose_name_plural': 'Style',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('house', models.CharField(max_length=200)),
                ('property_address', models.CharField(max_length=300)),
                ('zipcode', models.CharField(max_length=15)),
                ('lattitude', models.FloatField(blank=True)),
                ('longitude', models.FloatField(blank=True)),
                ('furnished', models.BooleanField(null=True)),
                ('price', models.FloatField()),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('garden', models.BooleanField(default=False, null=True)),
                ('pool', models.BooleanField(default=False, null=True)),
                ('parking', models.BooleanField(default=False, null=True)),
                ('property_desc', models.TextField()),
                ('location_desc', models.TextField()),
                ('built_year', models.IntegerField()),
                ('short_sale', models.BooleanField()),
                ('Foreclosure', models.BooleanField()),
                ('property_size_in_sqrfeet', models.FloatField()),
                ('property_size_in_acres', models.FloatField()),
                ('featured', models.BooleanField()),
                ('property_image', models.ImageField(upload_to='')),
                ('area', models.CharField(max_length=220)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyerapp.City')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyerapp.PropertyType')),
                ('sale_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyerapp.SaleStatus')),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyerapp.Style')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyerapp.City')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Area',
            },
        ),
    ]
