# Generated by Django 3.0.5 on 2020-05-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyerapp', '0002_auto_20200518_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='mls_no',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
